bblimke/webmock

lib/webmock/request_pattern.rb
In this branch, we already know that @query_params is not nil. Looks like this was the result of a copy-pasta. :P
=> Remove unnecessary @query_params.nil? check

lib/webmock/request_stub.rb
This PR allows a more intuitive approach when using RSpec.
Since double and mock in RSpec already permit a `.and_return` syntax,
mimic this behaviour in webmock for easier reading and integration.
=> Allow RSpec like syntax

lib/webmock/http_lib_adapters/http_gem_adapter.rb
Currently the loaders assume that the http gem is there as long as "require 'http'" doesn't fail -- which doesn't work well for codebases with a file called "http".
This pull request resolves that by making the HTTP gem detection work more like how all the other detectors work.
=> Detect presence of HTTP gem a little more cleanly.

lib/webmock/http_lib_adapters/em_http_request/em_http_request_1_x.rb, spec/acceptance/em_http_request/em_http_request_spec.rb
em-http-request allows you to send multiple requests on the same
EM::HTTPConnection object, which is mostly useful for pipelining.  If the
underlying TCP connection drops, it will be re-established if another
request is made on the same connection object.
In testing that a user of em-http-request correctly dealt with timeouts (by
retrying the request on the same connection object), it was discovered that
webmock does not correctly emulate the real-world behaviour of
em-http-request, and the parsed response data was being sent to the wrong
`EM::HTTPClient` instance.  This commit provides a failing test case (along
with a test case that succeeded already, to ensure the basic behaviour
continues to work in the future), along with a small change to the adapter
code to correctly handle the …
=> Fix em_http_request adapter for correct timeout+request handling

README.md
=> Fix README example with bad copy & paste

lib/webmock/util/query_mapper.rb, spec/unit/util/query_mapper_spec.rb
When symbols are keys, `QueryMapper#to_query` blows up with `TypeError: can't dup Symbol`.
=> Fix exception raised when keys are symbols

.travis.yml
Travis's new container-based infrastructure requires you to explicitly turn off `sudo`. No commands in this build use it, so compliance is as simple as specifying `sudo: false` in .travis.yml
=> Turn off sudo

spec/acceptance/http_rb/http_rb_spec.rb, spec/acceptance/http_rb/http_rb_spec_helper.rb, spec/acceptance/httpclient/httpclient_spec.rb, spec/spec_helper.rb
State of the world at d72af3d:
- Specs all pass on MRI 2.2.2 and JRuby 9000
- Two failures on MRI 1.9.3
- Three failures on JRuby 1.7.8
These are the only four versions I've been testing locally. I use rbenv instead of rvm and haven't implemented a way to run all specs across multiple versions in this project with my setup.
`spec/acceptance/http_rb/http_rb_spec.rb:57`
- 2-2-2 versions: `response.uri` is an `Addressable::URI` object
- 1.9.3 versions: `response.uri` is a `URI::HTTP` object
The spec could just call `#to_s` on both to pass, but that seems like a cop-out.
`spec/acceptance/httpclient/httpclient_spec.rb:121`
- 2.2.2 versions
- stubbing cookie header in first only => one request_signature has cookie header, other does not
- stubbing no headers => green
- stubbing cookie header in …
=> [WIP] Fix specs

lib/webmock/util/query_mapper.rb, spec/unit/util/query_mapper_spec.rb
Without this fix:
* Requests to:
http://www.google.com?query
* Stub registered as:
http://www.google.com?query=true
=> prevents form adding an extra =true to urls

spec/acceptance/patron/patron_spec.rb
warning: File.exists? is a deprecated name, use File.exist? instead
=> Remove a deprecated warning

README.md
I've been using webmock with RSpec 3.x and it seems to work fine. Maybe it's better to just say "RSpec is supported", just like with Minitest and Test::Unit.
=> Clarify RSpec support

webmock.gemspec
until we can update WebMock to support it
=> restricts HTTP rb version to < 1.0.0

README.md, lib/webmock/webmock.rb, spec/acceptance/shared/allowing_and_disabling_net_connect.rb
I have a situation where I would like Webmock to allow connections, except to **a number** of sites.
I could do that with a regular expression, but it can become quite unwieldy, and more as more sites are added to the list. Instead, I thought it would be better if I can pass a `call`-able (eg: Proc or lambda) as the `:allow` in `disable_net_connect!`. For example:
```Ruby
WebMock.disable_net_connect!(:allow => ->(url){ url.to_str.include?('httpstat') })
```
Does this make sense? Is this desiderable?
While implementing this, I noticed that there aren't good specs to cover the different formats accepted for `allow`, so I added that, then added a case for my proposal, as above.
The resulting spec (actually, shared example: `spec/acceptance/shared/allowing_and_disabling_net_connect.rb
`) …
=> Generic `:allow` descriptor

lib/webmock/http_lib_adapters/httpclient_adapter.rb, spec/acceptance/httpclient/httpclient_spec.rb
Recently I was using [vcr](https://github.com/vcr/vcr) along with [google-api-client](https://github.com/google/google-api-ruby-client) and had some issues with `vcr` recording the body of the responses. After some investigation, I realized that a request was done using `Hurley` (relies on `HTTPClient` and sends a block as well to get the chunks, however `webmock` was only calling that block but not taking care of storing the body of the response which resulted in an empty body.
=> Allow for webmock response to have body chunks

lib/webmock/http_lib_adapters/httpclient_adapter.rb, spec/acceptance/httpclient/httpclient_spec.rb
When manually specifying the Authorization header like
```Ruby
c = HTTPClient.new
c.request :get, uri.omit(:userinfo, :query), query, body, {'Authorization' => 'Basic #{digest}'}
```
instead of like:
```Ruby
c = HTTPClient.new
c.set_basic_auth(nil, 'username', 'password')
c.request :get, uri.omit(:userinfo, :query), query, body, headers
```
WebMock does not catch the username and password and does not put it in the uri. (not the missing username and password in the url)
```
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: GET http://localhost/some/endpoint
```
I would expect (note the username and password being present in the url):
```
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: GET …
```
=> HTTPClient: Fix manually specifying Authorization header

lib/webmock/util/query_mapper.rb, spec/unit/request_pattern_spec.rb, spec/unit/util/query_mapper_spec.rb
I went through the issues and saw nothing related to this. When stubbing requests, I was having difficult when dealing with a more complex structure (array of hashes).
Here the approach followed is iterate through the params and create a new hash on the array if the key already exists in the last hash.
=> Improve parsing of params on request

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_spec.rb
=> Only raises symbol headers exception if `RUBY_VERSION` < 2.3.0

lib/webmock/http_lib_adapters/httpclient_adapter.rb
This emits a warning when running a test suite with warnings enabled. Renaming the outer variables to name and value make it slightly more readable and removes the warning.
=> Don't shadow outer variable in reject! block.

spec/spec_helper.rb
spec_helper does potentially expensive check every time rspec starts
(waits for non responsive server 173.194.113.176, in theory only 5s, but in my experience a lot longer)
but if you want to repeatedly run a single non-network (e.g. unit) spec this is tiresome. In this modificatiion it will skip this expensive check if the env var NO_CONNECTION is already set.
=> make easier to run non-network specs quickly.

lib/webmock/util/query_mapper.rb, spec/unit/util/query_mapper_spec.rb
Fix the issue correctly raised by @timdiggins [here](https://github.com/bblimke/webmock/pull/590#commitcomment-16873516).
I took the specs that @timdiggins created and fix the issue.
One change was made to one of the specs since:
```
Rack::Utils.parse_nested_query("a[][b][]=one&a[][c][]=two") #=> {"a"=>[{"b"=>["one"], "c"=>["two"]}]}
```
=> Fix issue regarding hash with nested array

spec/support/network_connection.rb
`Object#timeout` is deprecated.
=> Resolve warning about `Object#timeout`

lib/webmock/util/headers.rb
WebMock uses base64 but it doe not load base64 by itself. It may cause `NameError: uninitialized constant WebMock::Util::Headers::Base64`.
=> WebMock should load "base64"

spec/acceptance/net_http/net_http_spec.rb
RSpec warns:
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass,
message)` risks false positives, since literally any other error
would cause the expectation to pass, including those raised by Ruby
(e.g. NoMethodError, NameError and ArgumentError), meaning the code you
are intending to test may not even get reached. Instead consider using
`expect {}.not_to raise_error`. This message can be supressed by setting:
`RSpec::Expectations.configuration.warn_about_potential_false_positives = false`
=> Resolve RSpec warning

lib/webmock/webmock.rb
Before this change:
```
> WebMock.net_connect_explicit_allowed?(/.*example.*/, 'http://example.com')
0
```
After:
```
> WebMock.net_connect_explicit_allowed?(/.*example.*/, 'http://example.com')
true
```
I was having trouble with some non-shareable case, this change fixes it.
=> Fix regex comparison

CHANGELOG.md, README.md, lib/webmock/util/headers.rb, spec/acceptance/shared/stubbing_requests.rb
if your `user:pass` string is long enough `Base64.encode64` will return a multiline value which breaks matching:
```
stub_request(:post, "https://example.com").with(basic_auth: [ 'useruseruseruseruseruseruseruseruseruser', 'passpasspasspasspasspasspasspass'])
Real HTTP connections are disabled. Unregistered request: POST https://example.com with headers {'Authorization'=>'Basic dXNlcnVzZXJ1c2VydXNlcnVzZXJ1c2VydXNlcnVzZXJ1c2VydXNlcjpwYXNzcGFzc3Bhc3NwYXNzcGFzc3Bhc3NwYXNzcGFzcw=='}
You can stub this request with the following snippet:
stub_request(:post, "https://example.com").
with(:headers => { 'Authorization'=>'Basic dXNlcnVzZXJ1c2VydXNlcnVzZXJ1c2VydXNlcnVzZXJ1c2VydXNlcjpwYXNzcGFzc3Bhc3NwYXNzcGFzc3Bhc3NwYXNzcGFzcw=='}).
to_return(:status => 200, :body => "", :headers => {})
registered …
```
=> use Base64.strict_encode64 to avoid trying to match against a multiline Authorization: header

lib/webmock/http_lib_adapters/excon_adapter.rb, lib/webmock/request_body_diff.rb, lib/webmock/util/version_checker.rb, spec/acceptance/em_http_request/em_http_request_spec.rb, spec/acceptance/httpclient/httpclient_spec.rb, spec/acceptance/httpclient/httpclient_spec_helper.rb, spec/acceptance/net_http/net_http_spec_helper.rb, spec/acceptance/shared/returning_declared_responses.rb, spec/acceptance/shared/stubbing_requests.rb, spec/acceptance/typhoeus/typhoeus_hydra_spec.rb
This is a collection of minor updates to remove Ruby warnings from the gem. These should all be very low risk changes. By fixing these warnings it helps to eliminate noise in projects which use the gem and have warnings enabled. It's always kind for gems to produce zero warnings if possible.
The most visible to projects that use `webmock` are the warnings coming from the `lib` directory. While I was running the specs I noticed that several additional warnings came from some spec support files. I went ahead and cleaned those up as well.
I left off the local changes I made to the `spec/spec_helper.rb` which expose the warnings when running the specs as that's more a decision the core team needs to make. Also, JRuby has some gems like `manticore` and `cookiejar` which produce a lot of …
=> Fix warnings

spec/acceptance/httpclient/httpclient_spec.rb
If the clock moves to next second during the spec run, date header might be different. Mock time to ensures that date headers of request signatures match.
=> Fix flaky HTTPClient adapter spec

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_spec_helper.rb
Net::HTTP raises a `Net::OpenTimeout`, a subclass of `Timeout::Error`, on open timeouts. It used a different class in 1.9 vs 2.x: https://github.com/ruby/ruby/commit/09f27873ed653bd4afb5538b669e2362f3b1bf6e
This is relevant because libraries like Faraday implement specific behavior on `Net::OpenTimeout`: https://github.com/lostisland/faraday/blob/v0.9.2/lib/faraday/adapter/net_http.rb#L28 and it can cause significantly different error handling in production vs under webmock.
This PR could may cause consumer's tests to break if they are asserting on the timeout class by name instead of hierarchy, but it implements the actual behavior of the library being stubbed.
=> Correct Net::HTTP open timeout exception class

lib/webmock/http_lib_adapters/net_http.rb, lib/webmock/request_stub.rb
This PR made the following changes in preparation Ruby 2.4.
- Fix deprecated warnings caused by [unifies Fixnum and Bignum into Integer](https://bugs.ruby-lang.org/issues/12005)
- Fix failure test caused by [add keyword arguments for Net::BufferedIO#initial attributes](https://github.com/ruby/ruby/commit/dad2382270b8bcfc56a0e2dd73c6201e63ed1a7c#diff-00a99d8c71daaf5fc60a050da41f7261L82)
=> Support Ruby 2.4

lib/webmock/util/query_mapper.rb, spec/unit/util/query_mapper_spec.rb
@bblimke 
People who have opted in to the `frozen_string_literal: true` Ruby 2.3 option, which makes all string literals frozen/immutable by default, will run into an error when attempting to use the `query` option in `webmock`.
This option causes all string literals to be frozen. I've imitated this in the test with an explicit `freeze` call on the argument. This will be the default on Ruby 3. More details on this Ruby 2.3 option are at https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3.
The `force_encoding` call here was causing a `can't modify frozen String` error when this setting was enabled because, like the webmock docs, I was passing in a string literal for the query.
Running the new test locally without the query mapper change results in this error:
``` …
```
=> Don't mutate the query argument

spec/acceptance/httpclient/httpclient_spec.rb
There are two tests which fails without network connection:
~~~
Failures:
1) HTTPClient httpclient streams response sets the full body on the webmock response
Failure/Error:
do_get_block_without_webmock(req, proxy, conn) do |http_res, chunk|
body += chunk
block.call(http_res, chunk)
end
SocketError:
getaddrinfo: Name or service not known (www.example.com:80)
2) HTTPClient credentials are detected when manually specifying Authorization header
Failure/Error: do_get_block_without_webmock(req, proxy, conn)
SocketError:
getaddrinfo: Name or service not known (www.example.com:80)
~~~
This PR marks them to require network connection, but may be the stub should be different? Not really sure ....
=> Some tests require network connectivity.

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_shared.rb
The implementation of WebMockNetBufferedIO is ignoring the read_timeout values passed during creation. With Ruby MRI 2.3.3 [1] this works, since the value is updated later on, but Ruby MRI 2.4.0 [2] is not doing that anymore.
[1] https://github.com/ruby/ruby/blob/v2_3_3/lib/net/http.rb#L904
[2] https://github.com/ruby/ruby/blob/v2_4_0/lib/net/http.rb#L955
=> Ensure the correct read_timeout value is used

lib/webmock/request_registry.rb, lib/webmock/util/hash_counter.rb, spec/unit/request_registry_spec.rb
Fixes https://github.com/bblimke/webmock/issues/606
We had the same
```
can't add a new key into hash during iteration
```
issue in our specs, and I think the [issue](https://github.com/bblimke/webmock/issues/606) above did capture the cause.
My naive try here seemed to fix the problem for us, but as I don't fully understand the details, this may not be a good solution. Still thought I would PR it and get feedback. Happy to iterate on this and add some specs.
=> Synchronous hash counter access from request registry.

lib/webmock/util/hash_counter.rb
Here's a fix for a Ruby warning.
The following is a sample of reproduction.
```sh
% ruby -we 'def foo(&block); proc &block; end'
-e:1: warning: `&' interpreted as argument prefix
```
Thanks.
=> Suppress `warning: `&' interpreted as argument prefix`

lib/webmock/http_lib_adapters/http_rb/streamer.rb, spec/acceptance/http_rb/http_rb_spec.rb
Since HTTP::Response::Streamer is returned instead of a HTTP::Connection, and HTTP::Connection responds to #close, HTTP::Response::Streamer should then also respond to #close.
I encountered this error when some code wanted to manually close the connection:
```rb
response.connection.close
```
=> Implement #close on HTTP::Response::Streamer

lib/webmock/http_lib_adapters/curb_adapter.rb, lib/webmock/http_lib_adapters/excon_adapter.rb, lib/webmock/http_lib_adapters/net_http.rb, lib/webmock/http_lib_adapters/patron_adapter.rb, lib/webmock/rack_response.rb, lib/webmock/request_execution_verifier.rb, lib/webmock/request_pattern.rb, lib/webmock/request_registry.rb, lib/webmock/request_signature.rb, lib/webmock/request_signature_snippet.rb, lib/webmock/stub_request_snippet.rb, lib/webmock/util/headers.rb, lib/webmock/util/query_mapper.rb, minitest/webmock_spec.rb, spec/acceptance/httpclient/httpclient_spec.rb, spec/acceptance/net_http/net_http_shared.rb, spec/acceptance/net_http/net_http_spec.rb, spec/acceptance/patron/patron_spec_helper.rb, spec/acceptance/typhoeus/typhoeus_hydra_spec_helper.rb, spec/unit/request_execution_verifier_spec.rb, test/shared_test.rb
These changes cover webmock's use of string literals, ensuring that it's able to be used with the MRI 2.3+ feature of frozen string literals enabled.
The caveats are as follows:
* Rack is not yet compatible, though [I have submitted a PR](https://github.com/rack/rack/pull/1182)
* Addressable is not yet compatible, though [I have submitted a PR](https://github.com/sporkmonger/addressable/pull/260)
* RSpec is compatible, but not yet in a released version.
* HTTPClient, Patron, em-http-request and perhaps other external dependencies are not yet compatible.
To test, I've been using the `pragmater` gem to add the pragma comment to all files in lib, spec, test and minitest, as well as using my fork of rack and addressable, plus the latest from the rspec repos, and then running the test suite. …
=> Updates for frozen-string-literal compatibility.

lib/webmock/http_lib_adapters/http_rb/webmock.rb, spec/acceptance/http_rb/http_rb_spec_helper.rb
HTTP.rb should raise a HTTP::TimeoutError rather than a HTTP::ConnectionError
when raising a timeout error.
=> Patch raise_timeout_error for HTTP.rb adapter to return proper error

spec/acceptance/typhoeus/typhoeus_hydra_spec.rb
Typhoeus::Response::Header becomes delegated class instead of Hash
subclass from 1.3.0.
=> Support typhoeus 1.3.0

lib/webmock/http_lib_adapters/httpclient_adapter.rb, spec/acceptance/httpclient/httpclient_spec.rb
By following code to reproduce, it doesn't call block.
Server:
```
#!/usr/bin/env ruby
require 'socket'
TCPServer.open("", 0) do |serv|
addr = serv.addr
puts "port: #{addr[1]}"
while true
Thread.start(serv.accept) do |s|
print(s, " is accepted\n")
p s.readpartial 900
s.write "HTTP/1.1 200 OK\nContent-Type: text/html\n\n"
s.close
end
end
end
```
Client:
```
require'httpclient'
HTTPClient.new.get("http://localhost:53503"){|r,c|p [r,c]}
```
=> HTTPClient doesn't yield block on empty body

lib/webmock/http_lib_adapters/http_rb/request.rb
http.rb 3.0.0 have introduced HTTP::Request::Body abstraction (https://github.com/httprb/http/pull/412) - let's make webmock compatible with it.
=> Make it compatible with the newest http.rb version (3.0.0)

lib/webmock/rspec.rb
When using [ruby-codacy-coverage](https://github.com/codacy/ruby-codacy-coverage) we were forced to whitelist Codacy by hand, even though the code coverage was being sent long after the entire test suite has run (in `at_exit` block in [simplecov](https://github.com/colszowka/simplecov)).
This was a surprising behaviour as the point of requiring `webmock/rspec` is to have a seamless integration that doesn't interfere with other tooling.
This PR changes the default behaviour of `webmock/rspec` so it does not by default interfere with test configuration.
=> Automatically disable WebMock after rspec suite

lib/webmock/http_lib_adapters/curb_adapter.rb
Using VCR with WebMock and curb in a test , there is a case that a redirection is performed and want to record it using VCR.
The test is something like this 
``` 
VCR.use_cassette('test_ok', :record => :new_episodes) do
end
```
and configuration is something like this
```
VCR.configure do |config|
config.cassette_library_dir = 'vcr_cassettes'
config.hook_into :webmock
config.before_http_request do
Thread.current[:curb_curl] = Curl::Easy.new
end
end
```
When the test runs for the first time it passes, but if it is re-executed it fails with the following error:
```
HttpClientError: undefined method `http_GET_without_webmock' for #<Curl::Easy http://www.example.com>
/Users/user01/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/webmock-1.21.0/lib/webmock/http_lib_adapters/curb_adapter.rb:139:in …
```
=> Redirection using curb fails with HttpClientError: undefined method `http_GET_without_webmock'

lib/webmock/util/json.rb
This fixes the following warning that is printed when using Ruby 2.5.0:
```
lib/webmock/util/json.rb:27: warning: assigned but unused variable - pos
```
=> Remove unused `pos` variable to fix Ruby warning

lib/webmock/stub_request_snippet.rb, spec/unit/stub_request_snippet_spec.rb
Currently when there is only header the output will seem like
```
stub_request(:post, "http://www.example.com/").
with(  headers: {
\t  'Accept'=>'application/json'
}).
to_return(status: 200, body: \"{}\", headers: {})
```
But it will be more consistent with the case that body is also included,
to be like
```
stub_request(:post, "http://www.example.com/").
with(  
headers: {
\t  'Accept'=>'application/json'
}).
to_return(status: 200, body: \"{}\", headers: {})
```
when
```
stub_request(:post, "http://www.example.com/").
with(
body: "abcdef",
headers: {
\t  'Content-Type'=>'multipart/form-data; boundary=ABC123'
}).
to_return(status: 200, body: \"\", headers: {})
```
=> Fix output when there is only header

lib/webmock/http_lib_adapters/curb_adapter.rb, spec/acceptance/curb/curb_spec.rb
=> Add `reset` method in curb adapter

lib/webmock/util/hash_counter.rb
On line 5 the reference to `Util` resolves to the class that was just opened on line 4, so `Util::` is redundant.
FYI @bblimke
=> Fix redundant `Util::` namespacing

lib/webmock/http_lib_adapters/net_http.rb
This PR fixes the following build error in Ruby 2.6.0 (ruby-head).
```console
$ ruby --version
ruby 2.6.0dev (2018-03-07 trunk 62693) [x86_64-linux]
% bundle exec rake
(snip)
1) Net:HTTP with WebMock when net connect is allowed should make a
real https request if request is not stubbed
Failure/Error: response = super(request, nil, &nil)
Net::ReadTimeout:
Net::ReadTimeout
Shared Example Group: "allowing and disabling net connect" called
from ./spec/acceptance/webmock_shared.rb:25
Shared Example Group: "with WebMock" called from
./spec/acceptance/net_http/net_http_spec.rb:10
request'
request'
`start_with_connect_without_finish'
in http_request'
`start_without_connect'
`http_request'
#
./spec/acceptance/shared/allowing_and_disabling_net_connect.rb:14:in
`block (4 levels) in <top (required)>' …
```
=> Prevent `Net/ReadTimeout` error in Ruby 2.6

lib/webmock/request_pattern.rb, lib/webmock/util/uri.rb, spec/unit/request_pattern_spec.rb
Fix #489 
`Addressable::Template#match` expects a valid uri with scheme
https://github.com/sporkmonger/addressable/issues/208#issuecomment-162404607
It works with most cases without uri scheme, but it raises an error with some cases like `127.0.0.1:8080`.
I've found that it causes the error when using webmock with [System Spec](https://relishapp.com/rspec/rspec-rails/docs/system-specs/system-spec) and chrome driver.
Always pass a uri with scheme to `Addressable::Template#match`. 
The difference from #739 is 
- adding a spec 
- making failing specs pass
=> Fix invalid scheme error with Addressable::Template

README.md, lib/webmock/api.rb, spec/acceptance/excon/excon_spec.rb, spec/acceptance/shared/callbacks.rb, spec/unit/api_spec.rb
=> Add API to reset registry requests

spec/acceptance/excon/excon_spec.rb, spec/acceptance/shared/callbacks.rb
They have changed their site to return an empty response if Accept is not specified.
Fixes the tests that depend on those responses.
Related to https://github.com/Readify/httpstatus/pull/49
=> Add Accept header to real calls in http://httpstat.us

lib/webmock/http_lib_adapters/net_http.rb
Ruby-head has introduced the following commit:
https://github.com/ruby/ruby/commit/bd7c46a7aa8b4f44ef683e22f469033b96d3dd5f#diff-8c2ab8e0fb4f052e1d95ab6334e192c1
It introduces a `write_timeout` keyward arg to BufferedIO, and this keyward arg gets set by Net::HTTP. This is causing failures when trying to run webmock on ruby-head since WebMockNetBufferedIO does not know about this keyword.
You can see a sample stacktrace here:
https://travis-ci.org/arkadiyt/ssrf_filter/jobs/398511410
```
Failure/Error: http.request(request)
ArgumentError:
unknown keyword: write_timeout
``` 
This PR fixes the issue by adding the keyword arg. Running against this version locally on ruby-head all my tests pass again.
Thanks,
=> Add write_timeout keyword arg to WebMockNetBufferedIO

.travis.yml
This PR only updates the versions of Rubies in CI.
See https://github.com/rbenv/ruby-build/tree/master/share/ruby-build for versions used.
=> Travis: use latest patch releases

.travis.yml
These MRIs has been released.
- https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/
- https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-4-5-released/
- https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-3-8-released/
- https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-2-10-released/
=> Use the latest MRIs on Travis CI

lib/webmock/http_lib_adapters/net_http.rb
if `super` raise an exception, this very danger TracePoint is not disabled.
This is why https://bugs.ruby-lang.org/issues/15400
This change is introduced at: https://github.com/bblimke/webmock/pull/751
Anyway, this approach is very danger (for example, `tmp` variable name is not exposed API), so that pls re-consider to use this technique.
=> disable TracePoint properly

lib/webmock/util/query_mapper.rb, spec/acceptance/shared/request_expectations.rb, spec/acceptance/shared/stubbing_requests.rb, spec/unit/util/query_mapper_spec.rb
With the following setup:
```ruby
let(:include_param) { [] }
let(:request_id)    { SecureRandom.uuid }
let(:result_body)   { { events: [{ type: event_type }] } }
let(:uri)           { "https://api.covermymeds.com/requests/#{request_id}/events" }
let!(:get_request_stub) do
stub_request(:get, uri)
.with(
query: { v: 'root_v1', include: include_param },
headers: { "Authorization" => "Bearer ..." })
.to_return(
body:   result_body.to_json,
status: 200,
)
end
context '#get_request' do
subject { client.get_request ... }
end
```
This test passes with Faraday <= 0.15.1
But a recent [change to Faraday](https://github.com/lostisland/faraday/pull/801) in how empty arrays are handled as query params causes the above test to fail:
```
Unregistered request: GET …
```
=> Handle and empty array as a query param

lib/webmock/webmock.rb, spec/unit/webmock_spec.rb
https://github.com/bblimke/webmock/issues/774
Currently there's `WebMock.allow_net_connect!` and `WebMock.disable_net_connect!`. 
For readability and memorability we should add `enable_net_connect!` and `disallow_net_connect` because enable suggests it should be disable.
=> Add aliases of enable_net_connect and disallow_net_connect

lib/webmock/http_lib_adapters/curb_adapter.rb, spec/acceptance/curb/curb_spec.rb
I feel like each request should not care about what is the previously called HTTP verb.
For example:
```
c = Curl::Easy.new("http://www.google.co.uk")
c.http_post
c.perform
```
In this case, c.perform http_verb would be set automatically to POST, which is an surprise. If it's default to GET, it feels more intuitive. Since we're already familiar with the notion of stateless request, which is independent from each other.
=> [ready] perform should reset webmock_method after making request

Rakefile
and make it non-executable. As there's no need for it.
=> Remove shebang from Rakefile

lib/webmock/request_body_diff.rb, webmock.gemspec
Why This Change Is Necessary
========================================================================
The `hashdiff` gem is changing its constant and thus we need to do the
same.
How These Changes Address the Issue
========================================================================
Update `HashDiff` references to `Hashdiff`.
Side Effects Caused By This Change
========================================================================
This will not remove the `hashdiff` warning error until `hashdiff`'s
`1.0` version is released, at which point a `bundle update` will remove
the warning.
------------------------------------------------------------------------
Actions:
* References #822
=> Update `Hashdiff` Constant

webmock.gemspec
=> Removed rubyforge_project from gemspec.

lib/webmock/http_lib_adapters/net_http.rb
ruby 2.6.x, stripe library in spec recorded with vcr/webmock
```
NoMethodError:
undefined method `write_timeout=' for #<StubSocket:0x0000556a9cca6f50 @read_timeout=80>
```
=> Support write_timeout setter in StubSocket

lib/webmock/util/uri.rb, spec/unit/util/uri_spec.rb
:80 / :443 was removed no matter where it appeared in the url, ie
also in path or authentication sections. Fixed by using URI to remove
the port rather than regexps
See also #827
=> Fix overeager removal of default ports from urls when matching

lib/webmock/http_lib_adapters/net_http.rb, spec/support/webmock_server.rb
I observed builds randomly failing, mostly on linux with EPIPE errors.
I *think* this is webrick closing the connection before the client has sent the request. This change makes webrick wait for the first byte of the request before sending a response.
There was another failure that was because we weren’t passing through the exception:false flag to rbuf_fill causing it to raise exceptions the net http code wasn’t expecting.
=> Fix a sporadic spec error

lib/webmock/http_lib_adapters/patron_adapter.rb
The regular expression applied to the HTTP status line only supports strings starting with "HTTP/x.x". However, HTTP/2 status lines won't use the dot.
=> Fix to support HTTP/2 status lines

lib/webmock/http_lib_adapters/async_http_client_adapter.rb
This fixes the following warning.
```
/usr/local/bundle/gems/webmock-3.7.0/lib/webmock/http_lib_adapters/async_http_client_adapter.rb:199: warning: shadowing outer local variable - v
```
=> Fix "warning: shadowing outer local variable - v"

lib/webmock/http_lib_adapters/em_http_request_adapter.rb, spec/acceptance/em_http_request/em_http_request_spec_helper.rb
As defined in a test, that's the expected error class:
https://github.com/igrigorik/em-http-request/blob/907f46713e8257e1c1dd348bc5da77adc8d38392/spec/client_spec.rb#L499
=> Fix EM HTTP request adapter's timeout class

lib/webmock/util/uri.rb, spec/unit/util/uri_spec.rb
After #832, if the URL contains incompatible encoding characters the gsub to remove the protocol relative from the URL will fail. We should encode the string to binary mode before doing the gsub.
Got the tests from https://github.com/bblimke/webmock/pull/687 since it is the same issue so this doesn't regress anymore.
=> Do not try to gsub on incompatible encoding

lib/webmock/http_lib_adapters/http_rb/streamer.rb, spec/acceptance/http_rb/http_rb_spec.rb
Unmocked:
```
> response = HTTP.get "http://example.com/foo"
> response.body.readpartial(1024, "")
"Hello world!"
```
Mocked:
```
> response = HTTP.get "http://example.com/foo"
> response.body.readpartial(1024, "")
ArgumentError: wrong number of arguments (given 2, expected 0..1)
```
`HTTP::Response::Body` delegates `#readpartial` to the underlying connection. For an unmocked request, that’s an `HTTP::Connection`, which accepts the conventional second argument to `#readpartial`. For a mocked request, it’s an `HTTP::Response::Streamer`, which previously *didn’t* accept a second argument.
=> Allow passing an output buffer to HTTP::Response::Body#readpartial

webmock.gemspec
Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `wiki_uri` and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/webmock and be available via the rubygems API after the next release.
=> Add project metadata to the gemspec

lib/webmock/http_lib_adapters/curb_adapter.rb, spec/acceptance/curb/curb_spec.rb
Exactly the same issue as in https://github.com/bblimke/webmock/issues/703 bites again!
I was running into a problem with VCR recording the same headers for a series of different Curl requests. Turns out it was due to partial `reset` method implementation, which only cleans up `body_str`, although `Curl::WebMockCurlEasy` memoizes a lot more things, including `header_str` for my case.
=> Reset memoized response fields in Curb adapter

lib/webmock/http_lib_adapters/excon_adapter.rb, spec/acceptance/excon/excon_spec_helper.rb
WebMock adapter for [excon](https://github.com/excon/excon) generates the following warning when sending a request:
```
[excon][WARNING] Invalid Excon connection keys: :__construction_args
```
This happens because excon [validates if all parameters provided are indeed valid connection parameters](https://github.com/excon/excon/blob/514db813e58453bb7a6bbd65751ba04b8e8a343b/lib/excon/connection.rb#L414-L425), and `:__construction_args`, WebMock's internal storage parameter, is not.
This PR adds `:__construction_args` to excon's [list of valid connection parameters](https://github.com/excon/excon/blob/514db813e58453bb7a6bbd65751ba04b8e8a343b/lib/excon/constants.rb#L68-L105).
This list has existed since excon's minimum version supported by WebMock: …
=> Suppress excon warning generated by extra key

lib/webmock/http_lib_adapters/async_http_client_adapter.rb
This PR suppresses the following keyword argument warnings when using Ruby 2.7.
```console
% ruby -v
ruby 2.7.0dev (2019-09-14T09:21:37Z master 39c37acf86) [x86_64-darwin17]
% bundle exec rake
/Users/koic/src/github.com/bblimke/webmock/lib/webmock/http_lib_adapters/async_http_client_adapter.rb:43:
warning: The last argumr
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/async-http-0.48.2/lib/async/http/client.rb:41:
warning: for `initie
/Users/koic/src/github.com/bblimke/webmock/lib/webmock/http_lib_adapters/async_http_client_adapter.rb:44:
warning: The last argumr
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/async-http-0.48.2/lib/async/http/client.rb:41:
warning: for `initie
```
cf. https://bugs.ruby-lang.org/issues/14183
=> Suppress keyword argument warnings in Ruby 2.7

lib/webmock/http_lib_adapters/net_http.rb
Webmock is currently showing a warning on Ruby 2.7 related to the use of
a single asterisk for passing keyword args to `BufferedIO` via the use
of an argument-less `super`.
Here's the warning:
```
/Users/brandur/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/webmock-3.7.6/lib/webmock/http_lib_adapters/net_http.rb:271: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/brandur/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/protocol.rb:114: warning: The called method `initialize' is defined here
```
And here's the method in question:
``` ruby
class WebMockNetBufferedIO < BufferedIO
def initialize(io, **args)
io = case io
when Socket, OpenSSL::SSL::SSLSocket, IO
io
when StringIO
PatchedStringIO.new(io.string)
when String …
```
=> Ruby 2.7: Use keyword args double-asterisk in `WebMockNetBufferedIO`

lib/webmock/http_lib_adapters/http_rb/response.rb, spec/acceptance/http_rb/http_rb_spec.rb
HTTP::Response::Body uses Encoding::BINARY as the default: https://github.com/httprb/http/blob/v4.3.0/lib/http/response/body.rb#L19
The failure without the patch looks like this:
```ruby
$ bundle e rspec -r ./spec/spec_helper.rb -e 'HTTP.rb streamer can be read to a provided buffer'
Run options: include {:full_description=>/HTTP\.rb\ streamer\ can\ be\ read\ to\ a\ provided\ buffer/}
HTTP.rb
streamer
can be read to a provided buffer (FAILED - 1)
Failures:
1) HTTP.rb streamer can be read to a provided buffer
Failure/Error: expect(buffer).to eq "Hello world! "
expected: "Hello world! "
got: "Hello world! \xEF\xA3\xBF"
(compared using ==)
Finished in 0.17638 seconds (files took 2.02 seconds to load)
1 example, 1 failure
Failed examples:
rspec ./spec/acceptance/http_rb/http_rb_spec.rb:75 # …
```
=> Be able to mock non-ASCII bodies with HTTP.rb

lib/webmock/request_pattern.rb, lib/webmock/stub_registry.rb, spec/unit/request_pattern_spec.rb
This PR allows providing any object which responds to `#call` as a URI pattern. This allows a lot more flexibility and accuracy than using a regex. One of the incentives for making this change is also that specifying a regex will call `variations_of_uri_as_strings` which is very slow. It's also much easier to stub all requests
The first commit is just a refactor of URIPattern and its subclasses, which makes introducing the new subclass as simple as possible.
This also changes `register_global_stub` to use `->(uri) {  true }` instead of `/.*/`, which is many times faster since it doesn't have to expand the URL patterns to perform the match.
=> Allow using a "callable" (like a proc) as URI pattern 

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_spec.rb
Hi there!
I'm writing an app that calls some methods from the bundler gem programmatically. I don't want to spam the rubygems API, so I'm trying to use VCR and webmock to record my test requests. 
Now bundler (2.0.2) does some funky low-level stuff with Net::Http sockets that currently cause the following exception when used in conjunction with Webmock and VCR:
```
NoMethodError:
undefined method `io' for #<StubSocket:0x00007fde11d49508 @read_timeout=10>
```
Specifically, this is the result of a call to [Bundler::Definition#resolve_remotely](https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L154), and the immediate call triggering the exception is [this](https://github.com/bundler/bundler/blob/master/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb#L …
=> stubbing io on stubbed socket

.travis.yml
This PR updates the CI matrix to use latest releases. **Update**: too early for rvm! Seems these named versions from the https://www.ruby-lang.org/en/news/ from today are not yet available.
- Use different JDKs for 9.1 and 9.2+
=> CI: Use new Ruby, separate out JRuby

lib/webmock/rspec.rb, spec/acceptance/shared/stubbing_requests.rb
I was recently working on mocking out some requests and ran into an issue where I was using webmock to forward mocked requests to a rack app.
I had wrapped a bunch of specs like:
```
Rspec.configure do |config|
config.around(:each) do |example|
some_mocking_setup
example.run  # <- makes a bunch of requests to the mocked endpoints
some_mocking_teardown # <- uses some of my mocked requests to tell the rack service to reset 
end
end
```
And was surprised when `some_mocking_teardown` was throwing errors about me attempting my mocking teardown.
I am able to successfully accomplish what I need by doing:
```
Rspec.configure do |config|
config.before(:each) do |example|
some_mocking_setup
example.run  # <- makes a bunch of requests to the mocked endpoints
end
config.after(:each) do |example| …
```
=> Reset webmock after all after(:each/example) hooks

lib/webmock/http_lib_adapters/async_http_client_adapter.rb
Problem: the server in Async::HTTP::WebMockEndpoint#accept_socket was
hanging forever after the rspec example finished.
This is normal as Async::HTTP::Server (or any server) is never supposed
to end. It just continues waiting for new requests which, in this case,
never come.
Solution: use a 'transient' async task when starting a server.
Transient tasks do not block an exiting async reactor.
So, in this case a transient server will not hang forever.
Fixes #858 
@ioquatix we talked about making this a draft PR so we can continue talking about a proper webmock <-> async-http solution. Since this fix is minimal I propose going for a merge.
We can continue thinking about a better approach here https://github.com/socketry/async-http/issues/35
=> Fix async http adapter

lib/webmock/http_lib_adapters/async_http_client_adapter.rb
Problem: when using async http adapter rspec outputs the following warning
`lib/webmock/http_lib_adapters/async_http_client_adapter.rb:154: warning: instance variable @alpn_protocol not initialized`
Reason for that is: `@alpn_protocol` is never defined.
Solution: don't use `@alpn_protocol`
=> Fix async http adapter warning

lib/webmock/request_pattern.rb, spec/unit/request_pattern_spec.rb
Fixes #903.
This reinstates `WebMock::Util::URI.normalize_uri` as the default fallback behavior of the constructor, specifically whitelisting callable objects, in addition to the classes that were previously whitelisted, to pass through unchanged.
Also corrected descriptions of some existing specs that didn't match tested behavior.
=> Revert inversion of pattern check in URIPattern constructor

CHANGELOG.md
This PR fixes the markdown in the CHANGELOG file to properly show missing links.
=> Fix CHANGELOG.md links

lib/webmock/stub_registry.rb
This fixes an issue where testing multi-threaded code could sometimes result in incorrect responses being returned. Specifically in the case of VCR, since it seems to mock a nil response first before stubbing the real value, a nil response could sometimes be returned. This was because the hash being used by global stubs is not thread-safe.
I tried to write a test for this, but given the multi-threaded nature, and the fact it doesn't happen on MRI, it was difficult to find anything that failed. The existing tests do at least regression test it though. And I've tested it extensively on the repo where I originally found the issue and it works well.
closes https://github.com/bblimke/webmock/issues/907
=> Make global stubs thread-safe

lib/webmock/http_lib_adapters/httpclient_adapter.rb
httpclient_adapter uses some standard Ruby hashes, which produce unexpected results when working in a true multi-threaded (e.g. JRuby) environment. Multiple threads doing puts and deletes on these hashes result in nils sometimes being returned for a properly stubbed request. These errors would manifest as:
`webmock-3.9.2/lib/webmock/http_lib_adapters/httpclient_adapter.rb:113:in build_httpclient_response: undefined method body for nil:NilClass (NoMethodError)`.
Unfortunately these errors are extremely difficult to replicate. I've only been able to reproduce it periodically when running a large suite of VCR tests. Therefore its difficult to write a spec around this. I've run this patch against our local test suite over 10 times and haven't been able to reproduce the error with it, so I'm …
=> Make httpclient_adapter threadsafe

lib/webmock/response.rb, spec/unit/response_spec.rb
Right now, users might be confused as to why a hash cannot be accepted
as a response body? See Issue #449 on Github as well as #427.
This seems to have caused considerable consternation
to API users - with some spending many frustrated hours searching for a
solution. Perhaps it can be solved with a more helpful exception
message? This PR hopes to remedy this apparent shortcoming. Perhaps
I shall remedy it with an update to the documentation as well.
I submit it with the utmost respect to the maintainers and community.
Thank you for your efforts, and for reviewing.
Ben
=> Fix: Clarify exception message

lib/webmock/stub_registry.rb, lib/webmock/webmock.rb, spec/acceptance/shared/stubbing_requests.rb
We have a similar problem as described in #171 in the project currently I'm working on. Since I did not found PR for this issue I created this one. 
By default, nothing is changed in the API but it is possible to give the `after_stubs` option while registering global stub. Then the global stub will be used only when no "local" stub is found.
=> Option to invoke local stub before global stub

lib/webmock/http_lib_adapters/async_http_client_adapter.rb
`async-http` switch to keyword arguments: https://github.com/socketry/async-http/commit/3e967d4ff729bb4f02587d3e5784fd5cf4e37c26
because its signature
`def initialize(endpoint, protocol = endpoint.protocol, scheme = endpoint.scheme, authority = endpoint.authority, retries: DEFAULT_RETRIES, connection_limit: DEFAULT_CONNECTION_LIMIT)` 
`def initialize(endpoint, protocol: endpoint.protocol, scheme: endpoint.scheme, authority: endpoint.authority, retries: DEFAULT_RETRIES, connection_limit: DEFAULT_CONNECTION_LIMIT)`
This should be the easist way to keeping compatibility
=> Compatible with async-http 0.54+

webmock.gemspec
This is required for Ruby 3.0, where the WEBrick was completely removed resulting in test failures such as:
~~~
$ bundle exec rake
/home/travis/.rvm/rubies/ruby-head/bin/ruby -I/home/travis/.rvm/gems/ruby-head/gems/rspec-core-3.10.1/lib:/home/travis/.rvm/gems/ruby-head/gems/rspec-support-3.10.1/lib /home/travis/.rvm/gems/ruby-head/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*/\*_spec.rb -c -f progress -r ./spec/spec_helper.rb
An error occurred while loading ./spec/spec_helper.rb. - Did you mean?
rspec ./spec/unit/response_spec.rb
Failure/Error: require 'webrick'
LoadError:
cannot load such file -- webrick
No examples found.
~~~
Fixes #924
=> Add WEBrick dependency

.github/workflows/CI.yml, Gemfile, Rakefile
* Force color on all tests
* Update supported Rubies
* Use https in Gemfile
Sample run: https://github.com/mlarraz/webmock/actions/runs/555468687
=> Use Github Actions for CI

lib/webmock/http_lib_adapters/async_http_client_adapter.rb, spec/acceptance/async_http_client/async_http_client_spec.rb
This was causing an issue in VCR, as callbacks were always firing because net connect was enabled. In this case, continuously appending recorded cassettes.
A stubbed request is not a real request, and therefore shouldn’t fire callbacks that are only meant for real requests.
Note this was made in collaboration with the fix identified by @ioquatix in #930
=> Async http adapter: only consider real requests to be real

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_spec.rb
Wrapped the hostname in brackets to separate it from the port, when it is an IPv6 address.
It is an attempt to fix the issue #806.
Is the `net_http_spec.rb` the right place for the added specs or should I rather put them into a new file `net_http_utility_spec.rb`?
=> Fix: Handle IPv6 hostname correctly (closes #806)

lib/webmock/http_lib_adapters/http_rb/response.rb, lib/webmock/http_lib_adapters/http_rb/webmock.rb
5.0.0 had a breaking change.
Fixes #940
I'm not completely sure this is the right fix, but my tests work now with both 4.4.1 and 5.0.0 of `http`.
=> Support http.rb 5.x

webmock.gemspec
This version fixes a ReDoS vulnerability in `Addressable::Template#match`
For more information about the issue:
- https://app.snyk.io/vuln/SNYK-RUBY-ADDRESSABLE-1316242
From addressable [CHANGELOG](https://github.com/sporkmonger/addressable/blob/main/CHANGELOG.md), it seems to not have breaking changes, and just ran the test-suite passed in my local without failures ✅
=> Bump Addressable from 2.3.6 to 2.8.0

CHANGELOG.md, lib/webmock/http_lib_adapters/async_http_client_adapter.rb
even if Socket::AF_UNIX is defined on Windows, it cannot be used, so let's use Socket::AF_INET as a fallback
=> fix async adapter on Windows

lib/webmock/request_stub.rb, spec/unit/request_stub_spec.rb
Make stubbing out json responses a little bit more convenient by
1) JSON-ifying Hash bodies
2) applying the Content-Type: application/json header
Some relevant discussion in #449
=> Add RequestStub#to_return_json

lib/webmock/http_lib_adapters/http_rb/response.rb, lib/webmock/http_lib_adapters/http_rb/streamer.rb, spec/acceptance/async_http_client/async_http_client_spec.rb, spec/acceptance/excon/excon_spec.rb, spec/acceptance/shared/allowing_and_disabling_net_connect.rb, spec/acceptance/shared/callbacks.rb, spec/acceptance/shared/complex_cross_concern_behaviors.rb, spec/unit/request_signature_spec.rb, spec/unit/response_spec.rb
httpstat.us switched to HTTPS and returning 301 for plain HTTP and now
there is no `X-Powered-By` header, use HTTPS + `Server` header instead.
`http.rb` >= 5.0.2 expects stream result to be in the proper encoding after https://github.com/httprb/http/pull/653, force encoding in `Streamer`.
=> Make CI green again

lib/webmock/http_lib_adapters/curb_adapter.rb, spec/acceptance/curb/curb_spec.rb
When using headers that contain more than one ":" character the resulting stubbed request will only contain a portion of the original header. This change will prevent the header from being split in more than 2 pieces.
Fixes: [#946 ](https://github.com/bblimke/webmock/issues/946)
=> Limit the number of splits when parsing headers in the Curb adapter

lib/webmock/request_signature.rb, spec/unit/request_signature_spec.rb
When using the HTTP gem with a command like `HTTP.post(url, json: { a: 1 })`, the `Content-Type`-header is set to `application/json; charset=UTF-8`. This currently prevents me from using the `RequestBodyDiff`-method, as a check for `json_headers?` is made, which returns false if the content type isn't exactly `application/json`.
Specifying the charset in the content type [should be allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#syntax). This PR therefore suggests just to check whether the content type starts with `application/json` instead of requiring an exact match.
The same is done for the `url_encoded?` helper method, checking for the `application/x-www-form-urlencoded` content type.
=> Allow content type headers to specify a charset

lib/webmock/http_lib_adapters/http_rb/client.rb, lib/webmock/http_lib_adapters/http_rb/webmock.rb
Fixes the bug mentioned in https://github.com/bblimke/webmock/pull/896#issuecomment-758270719
=> Prevent double-wrapping http.rb features on non-stubbed requests

CHANGELOG.md, README.md
This updates documentation to use the more inclusive `denylist` verbiage instead of `blacklist`.
=> Change `blacklist` to `denylist` in documentation

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_shared.rb
Take the following example:
```ruby
require 'net/http'
require 'webmock'
WebMock.enable!
WebMock.allow_net_connect!
http = Net::HTTP.new('example.org')
http.start
http.get('/')
http.get('/')
http.get('/')
http.finish
```
This example would create 3 sockets and only close one of them. That's because `start_with_connect_without_finish` spawns a new connection for each request, and never closes the previous one.
This PR also makes it so that when using a persistent connection, the `@socket` will be reused across requests. I believe this should totally fix the common "gotcha" that people encounter when combining WebMock with Capybara _without_ needing to enable `net_http_connect_on_start`.
I'd recommend reviewing this PR commit-by-commit. I tried to provide pretty detailed explanations for …
=> Fix leaky file descriptors and reuse socket for persistent connections

lib/webmock/http_lib_adapters/net_http.rb, lib/webmock/webmock.rb, spec/acceptance/net_http/net_http_spec.rb, spec/unit/webmock_spec.rb
Currently, `net_http_connect_on_start` is all or nothing. Many people only want to connect Selenium's requests on start so that WebMock and Capybara play nicely together.
Using `net_http_connect_on_start: true` has some undesirable behaviors (see #914 and #955). I think that this PR provides a workaround for those issues. For most people, I think `net_http_connect_on_start: %w(localhost 127.0.0.1)` will be a more ideal configuration.
This PR is backwards compatible.
=> Allow specifying when Net::HTTP should connect on start

webmock.gemspec
https://github.com/bblimke/webmock/pull/969 uses `&.`, but `&.` has been available since Ruby 2.3
c.f. https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/
webmock v3.15.0+ already doesn't work with Ruby < 2.3, so I fixed `required_ruby_version`
=> Requires Ruby 2.3+

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_spec.rb
Fixes https://github.com/bblimke/webmock/pull/976#issuecomment-1203449899
* ActiveMerchant expects `#ssl_version` and `#cipher` to be defined. Though these methods are private, it's best if webmock can *try* to act like the Net::HTTP to avoid gems having to detect if WebMock is enabled.
* I also took the opportunity to make `StubSocket#close` and `StubSocket#closed?` a bit more realistic as well.
* I also noticed that `Net::HTTP#ipaddr` was broken because `StubSocket#peeraddr` wasn't defined.
=> Make the StubSocket slightly more believable

webmock.gemspec
The "homepage" in the gemspec (and so in rubygems.org page) points this repo via http protocol, but it redirects to https when we actually visit the page.
=> Update homepage in the gemspec to be HTTPS

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_spec.rb, spec/acceptance/patron/patron_spec.rb
As of #989, this library requires Ruby >= 2.3, so the following changes were in order:
* The `validate_headers` function is only executed for Ruby versions prior to 2.3.
* The patron adapter had tests that were only run for Ruby 1.9. These tests should actually have been written for all Ruby versions _greater than_ 1.9.
=> Remove dead code for supporting Ruby < 2.3

lib/webmock/request_pattern.rb, spec/unit/request_pattern_spec.rb
We have a syntax error, `reutrn`, when matching on an array body.
=> Fix Syntax Error: `reutrn`

lib/webmock/http_lib_adapters/net_http.rb, lib/webmock/response.rb, spec/unit/response_spec.rb
Ruby's Net::BufferedIO doesn't hit the network; therefore, this library should not be patching it.
I believe that `WebMockNetBufferedIO` and `PatchedIO` were introduced so that a String could be used as a raw response. However; it's actually much simpler just to convert the string to a StringIO before attempting to parse the raw HTTP response.
=> Avoid replacing Net::BufferedIO

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_spec.rb
This PR aims to simplify the way that the stub socket is assigned and swapped in Net::HTTP.
=> Simplify Net::HTTP connection handing

README.md
RubyForge doesn't work anymore, so this points to the Github page.
=> fix FakeWeb link

lib/webmock/request_pattern.rb
Stubs using HashExcludingMatcher were not working because body is not being converted to a hash in order to do the matching
=> Fix matching stubs with HashExcludingMatcher

README.md
Escape regex special chars in example
=> README: Escape regex special chars in example

lib/webmock/util/version_checker.rb, spec/unit/util/version_checker_spec.rb
This should fix the error below
> You are using Curb 0.9.11. WebMock is known to work with Curb >= 0.7.16, < 1.1, except versions 0.8.7. It may not work with this version.
=> Fix version check when major version is less than the max version

lib/webmock/util/version_checker.rb, spec/unit/util/version_checker_spec.rb
For ex we are using Curb version 0.9.7 and it prints a warning even though it shouldn't
=> Version checker fails under some conditions

lib/webmock/util/uri.rb
Currently, `allow_localhost` option of `disable_net_connect!` method does not allow `[::1]` to be communicated, while this is actually an localhost address (of IPv6).
This PR should allow communicating with `http://[::1]/some/path` address.
=> add "[::1]" for localhost determination

lib/webmock/util/headers.rb
Optimizes the `WebMock::Util::Headers.normalize_headers` method to:
* Create less objects
* Avoid using Regexp where possible
* Hoists constants
More details can be found in the related issue, including performance benchmarks:
https://github.com/bblimke/webmock/issues/1027
=> Optimizes `normalize_headers` for performance

lib/webmock/http_lib_adapters/em_http_request_adapter.rb
Tiny tiny optimization PR
As per https://github.com/fastruby/fast-ruby/blob/main/code/enumerable/select-first-vs-detect.rb
Detect is slightly faster than select{}.first
=> EmHttpRequestAdapter - Call detect instead of select..first

lib/webmock/util/headers.rb, spec/acceptance/async_http_client/async_http_client_spec_helper.rb
Ruby 3.3 shows a warning when using base64 without declaring it in the gemspec. Ruby 3.4 will remove base64 as a default gem.
Since this gem is only using a single method in one place there is no need to pull in the full dependency. It is only a wrapper over `Array#pack`.
Alternative to #1041
Other gems have taken the same/similar approach:
* https://github.com/rubocop/rubocop/pull/12313
* https://github.com/rack/rack/pull/2110
* https://github.com/newrelic/newrelic-ruby-agent/pull/2378
* https://github.com/lostisland/faraday/pull/1541 (pending)
=> Remove runtime dependency on `base64`

spec/acceptance/async_http_client/async_http_client_spec.rb, spec/acceptance/async_http_client/async_http_client_spec_helper.rb
The `async` gem recently made a breaking API change that was released in patch version 2.6.4.[^1] Following the change, async tasks that return an  exception object will no longer raise that exception when `wait` is called.
The `Async::HTTP` specs in webmock were written to leverage the old behavior of `wait`. Since async 2.6.4 was released, these specs have been failing in CI.
This commit fixes the failing specs by updating how `wait` is used, such that exceptions are still raised as expected in async 2.6.4. This should restore CI to a working state.
Fixes #1036 
[^1]: https://github.com/socketry/async/pull/270
=> Fix failing Async::HTTP specs due to Async API change

lib/webmock/http_lib_adapters/typhoeus_hydra_adapter.rb, spec/acceptance/typhoeus/typhoeus_hydra_spec.rb
This sets all of the `*_time` fields from [Typhoeus::Response::Informations](https://www.rubydoc.info/github/typhoeus/typhoeus/Typhoeus/Response/Informations) to 0.0 when constructing the `Typhoeus::Response` objects.
It would be cool to have an API for mocking these; perhaps something like
```ruby
stub_request(:get, "http://www.example.com")
.to_return(status: 200)
.to_take(3.seconds)
```
but for now I just wanted to set them to a non-nil value
=> Set Typhoeus timing fields when constructing Response objects

lib/webmock/rack_response.rb, spec/spec_helper.rb, spec/support/my_rack_app.rb, spec/unit/rack_response_spec.rb
When I upgraded Rack, I got a few deprecation warnings regarding the usage of `Rack::VERSION` in `lib/webmock/rack_response.rb`.
This conditionally adds the key to the Rack environment, since not only it's [no longer required](https://github.com/rack/rack/blob/v3.0.1/UPGRADE-GUIDE.md#rackversion-is-no-longer-required) but it's also [deprecated](https://github.com/rack/rack/blob/v3.0.1/lib/rack/version.rb#L17).
I also added a commit to enable deprecation warnings by default, it's [not something that RSpec does](https://github.com/rspec/rspec-core/issues/2867) but it can be useful like in this case. Let me know (or just remove that commit) if you'd rather not have that.
=> Don't use deprecated Rack::VERSION in Rack 3

lib/webmock/http_lib_adapters/httpclient_adapter.rb, spec/acceptance/httpclient/httpclient_spec.rb
If a filter changes the URI (e.g. to enforce a protocol or change the hostname of the request) this is currently unable to be mocked as webmock fetches the URI for the signature of the request before calling the filters!
=> httpclient_adapter: use uri after filters when building request signature

README.md
While debugging the `net_http_connect_on_start` [gotcha with Capybara](https://github.com/teamcapybara/capybara#gotchas) I found it's sometimes necessary to restrict the scope of `net_http_connect_on_start` to prevent network connections to external services while allowing (and fixing) connections to the local test server.
This PR pulls information from [this comment](https://github.com/bblimke/webmock/issues/914#issuecomment-810134233) into the readme and adds an example to show `net_http_connect_on_start` accepts domains as well as boolean values, which resolved the issue for me.
=> Add net_http_connect_on_start example with explicit domain

lib/webmock/http_lib_adapters/async_http_client_adapter.rb, spec/acceptance/async_http_client/async_http_client_spec.rb
* Changed `Async::HTTP::WebMockClientWrapper#initialize` to use keyword arguments to match [Async::HTTP::Client#initialize](https://socketry.github.io/async-http/source/Async/HTTP/Client/index.html)
* Also initialize `Async::HTTP::WebMockClientWrapper#endpoint` (see #1060).
=> Fix `Async::HTTP::WebMockClientWrapper` mock interface

lib/webmock/request_pattern.rb, spec/unit/request_pattern_spec.rb
Tests are currently failing in `master` due to a change in the latest version of REXML.
REXML previously accepted some invalid XML (e.g. `foo bar`) but raised on other (`<foo bar`). Since [v3.3.3](https://github.com/ruby/rexml/releases/tag/v3.3.3) it also raises on `foo bar` (see https://github.com/ruby/rexml/pull/184).
Likewise, `WebMock::Util::JSON.parse` accepts some invalid JSON (e.g. `foo bar`) but raises on other (e.g. `[foo bar`).
It seems both matchers should just rescue and ignore parse exceptions.
=> Ignore parse exceptions

lib/webmock/http_lib_adapters/http_rb/streamer.rb, spec/acceptance/http_rb/http_rb_spec.rb
Mock [`HTTP::Connection#finished_request?`](https://github.com/httprb/http/blob/b74b16cd55381433627205c90bc126f9b81600ff/lib/http/connection.rb#L139C9-L141) in http.rb.
=> Mock HTTP::Connection#finished_request?

lib/webmock/http_lib_adapters/em_http_request_adapter.rb, spec/acceptance/em_http_request/em_http_request_spec.rb, spec/spec_helper.rb
The current version of em-http-request (1.1.7) is not compatible with Ruby HEAD (see https://github.com/igrigorik/em-http-request/pull/365).
Skip tests for the em-http-request integration on Ruby 3.4 for now in order to allow the other tests to complete.
Best reviewed with “ignore white-space”.
=> Exclude em-http-request on Ruby 3.4

lib/webmock/http_lib_adapters/net_http.rb
Closes #1088
This old constant was deprecated in 2001 and now finally removed. https://github.com/ruby/net-http/pull/189
It fixes this error:
```
/usr/local/bundle/bundler/gems/webmock-9ff63ac7c845/lib/webmock/http_lib_adapters/net_http.rb:25:in 'Module#remove_const': constant Net::HTTPSession not defined (NameError)
Net.send(:remove_const, :HTTPSession)
^^^^^
from /usr/local/bundle/bundler/gems/webmock-9ff63ac7c845/lib/webmock/http_lib_adapters/net_http.rb:25:in 'WebMock::HttpLibAdapters::NetHttpAdapter.disable!'
```
You can test it yourself by adding `gem 'net-http', github: 'ruby/net-http'` to the gemfile here and running tests.
I assume this will be released with 3.4
=> Resolve `net-http` adapter deprecation Ruby 3.4

lib/webmock/http_lib_adapters/httpclient_adapter.rb
This reverts commit c228536883c67514a62af03ddfd437d1e0a5d5d8 in #1091.
Since the CI is failing, the changes must ensure that the CI passes.
=> Revert "Fix included modules on Ruby 3.4"

Gemfile
This PR adds `ostruct` gem to Gemfile to fix the following Ruby 3.5 CI build error:
```console
An error occurred while loading ./spec/acceptance/typhoeus/typhoeus_hydra_spec.rb. - Did you mean?
rspec ./spec/acceptance/typhoeus/typhoeus_hydra_spec_helper.rb
Failure/Error: require 'ostruct'
LoadError:
cannot load such file -- ostruct
```
https://github.com/bblimke/webmock/actions/runs/13171078861/job/36761473227?pr=1097
Avoiding the use of `OpenStruct` is certainly an option, but since this module is only used in tests, the simplest solution has been chosen.
=> Add `ostruct` gem to Gemfile to prevent an error in development with Ruby 3.5

Gemfile
This is a workaround to resolve the following error in Ruby 3.5:
```console
/home/runner/work/webmock/webmock/vendor/bundle/ruby/3.5.0+0/gems/ethon-0.16.0/lib/ethon.rb:2:
warning: logger was loaded from the standard library, but is not part of the default gems starting from Ruby 3.5.0.
It can likely be removed once `ethon`, which is a dependency of `typhoeus`, manages its `logger` dependency.
```
https://github.com/bblimke/webmock/actions/runs/13170758361/job/36760571749
=> Fix a build error for Ruby 3.5 CI matrix

.github/workflows/CI.yml
This PR suspends JRuby CI matrix:
The issue has been reported at jruby/jruby#8606.
https://github.com/bblimke/webmock/actions/runs/13170199216/job/36759013080
The JRuby CI matrix has been failing for a long time, so pining to a version like JRuby 9.4.10.0 will not avoid the error. Since the issue is likely complex and not easy to resolve, it would be better to test with a version released after the resolution of jruby/jruby#8606.
=> Suspend JRuby CI matrix

lib/webmock/http_lib_adapters/typhoeus_hydra_adapter.rb, spec/acceptance/typhoeus/typhoeus_hydra_spec.rb
When stubbing a response for the Typhoeus adapter, and the Typhoeus request has an `on_body` callback, a `FrozenError` exception is raised when attempting to concatenate the current chunk of the response to the existing response body (i.e. `response.body << chunk`).
FWIW, my use case for this is to abort a request as early as possible when the response body exceeds a given size, specifically when the response doesn't have a `Content-Length` header.
The example below illustrates the issue:
```ruby
require "bundler/inline"
gemfile do
source "https://rubygems.org"
gem "typhoeus", "1.4.1"
gem "webmock", "3.24.0"
end
WebMock.enable!
WebMock.stub_request(:get, "https://example.com").to_return(status: "200", body: "body")
request = Typhoeus::Request.new("https://example.com")
request.on_body do …
```
=> Fix FrozenError in Typhoeus streaming response body
