bblimke/webmock

.travis.yml, README.md
=> Add MRI 2.2.1 to travis CI

README.md
rake task name changed in 9948087ffdb6e5b2bdca251987a2eaef0ed507d2
=> update readme to reflect rake task name change

lib/webmock.rb, spec/unit/webmock_spec.rb
Fixes https://github.com/bblimke/webmock/issues/496
=> require only the necessary parts of crack to avoid pulling in safe_yaml

lib/webmock/http_lib_adapters/net_http.rb, spec/acceptance/net_http/net_http_spec.rb
=> Mirror Net::HTTP handling of headers as symbols

lib/webmock/http_lib_adapters/manticore_adapter.rb, webmock.gemspec
Responding to breaking change in Manticore:
https://github.com/cheald/manticore/commit/174e2004d1865c201daf77494d50ab66527c12aa
=> Update manticore adapter to 0.5.x

Gemfile
=> Ruby 1.8.7 requires addressable < 2.4.0

lib/webmock/http_lib_adapters/net_http.rb
This patch is a fix for #558. Passes tests here, but I eagerly await the Travis tests against more Ruby versions.
=> Fix StringIO read_nonblock to match IO

README.md
=> document automatic enabling

lib/webmock/http_lib_adapters/curb_adapter.rb, spec/acceptance/curb/curb_spec.rb, spec/acceptance/curb/curb_spec_helper.rb, spec/spec_helper.rb, webmock.gemspec
This PR fixing issue: https://github.com/bblimke/webmock/issues/621
=> Fix curb on debug

Gemfile, lib/webmock/http_lib_adapters/curb_adapter.rb, spec/spec_helper.rb, webmock.gemspec
The feature to turn on debug for curb callbacks was deleted to. It's necessary implement again ):
=> Revert curb patch

spec/unit/api_spec.rb
Thanks, your work is very much appreciated!
=> Tweaked a spelling mistake in a test context

lib/webmock/http_lib_adapters/httpclient_adapter.rb
I moved them into the module where they really are used in. I tried tests (still green) and tried with an own project, where we are using rack-oauth2 gem (which uses httpclient). Tests were still running as expected. Since I did not add new functionality, I did not write any tests.
=> several methods for httpclient_adapter defined on main level

lib/webmock/api.rb, test/shared_test.rb
=> add refute_requested

README.md
Thank you for maintaining this awesome project!
=> Fix README typo: 'Authorization'

lib/webmock/http_lib_adapters/net_http.rb, lib/webmock/request_stub.rb
=> Revert "Support Ruby 2.4"

lib/webmock/http_lib_adapters/net_http.rb, lib/webmock/request_stub.rb
=> Revert "Revert "Support Ruby 2.4""

lib/webmock/rspec/matchers/webmock_matcher.rb
Don't know why these at_least matchers weren't included originally, but it seems like they should be there... :)
=> Add at_least matchers for fakeweb-style expectations

README.md
https://github.com/bblimke/webmock/issues/684
Appears in 3 places, so updated all.
=> Readme: Remove .* from regex.

lib/webmock/request_pattern.rb, lib/webmock/stub_request_snippet.rb, lib/webmock/util/headers.rb, spec/unit/request_signature_snippet_spec.rb, spec/unit/stub_request_snippet_spec.rb
=> Pretty print failure output

lib/webmock/util/values_stringifier.rb, spec/acceptance/shared/stubbing_requests.rb
=> do not convert HashIncludingMatcher to_s

lib/webmock/http_lib_adapters/manticore_adapter.rb
Solves https://github.com/bblimke/webmock/issues/810
=> Use Manticore::Response#on_complete to invoke callbacks

lib/webmock/request_pattern.rb, spec/unit/request_pattern_spec.rb, spec/unit/util/uri_spec.rb
Failing test for issue #828: RequestPattern does not match domain without period
=> Failing test for issue #828: RequestPattern does not match domain without period

README.md, lib/webmock.rb, lib/webmock/http_lib_adapters/async_http_client_adapter.rb, spec/acceptance/async_http_client/async_http_client_spec.rb, spec/acceptance/async_http_client/async_http_client_spec_helper.rb, spec/acceptance/shared/callbacks.rb, spec/acceptance/shared/returning_declared_responses.rb, webmock.gemspec
Add support for new asynchronous http library.
See https://github.com/socketry/async-http
=> Add support for Async::HTTP::Client

lib/webmock/http_lib_adapters/async_http_client_adapter.rb
=> Fix options handling.

lib/webmock/http_lib_adapters/net_http.rb
Why I think this is better than the previous work around made in https://github.com/bblimke/webmock/commit/1cc36e5d9a64f081cf83683752ceea6f04bf4ff5
- Maintenance complexity is likely lowered. Previous fix was susceptible to breaking whenever `rbuf_fill` was changed. This has the same concern in different ways though clearly references the code and is therefore easier to update. 
- Avoids the overhead cost of creating tracepoint, generating binding and disable
=> Replace rbuf_fill modification with duplication of core library

lib/webmock/http_lib_adapters/http_rb/response.rb
=> Support correct encoding parameter for HTTP.rb 2.x and earlier

README.md
Folks when reviewing will be able to quickly see what clients are supported.
=> Update Readme: Add note re: support for the HTTP gem

lib/webmock/http_lib_adapters/manticore_adapter.rb, spec/acceptance/manticore/manticore_spec.rb
This fixes https://github.com/bblimke/webmock/issues/926
=> Fix manticore streaming mode when WebMock is enabled

spec/unit/request_pattern_spec.rb
Similar to cb3d92965ff422845cecd68f461d807d0b87a0dc ☺️
=> Fix copy-paste of JSON instead of XML in spec file

lib/webmock/http_lib_adapters/em_http_request_adapter.rb, spec/acceptance/em_http_request/em_http_request_spec.rb
This appears to fix #899. em-http-request is such a ball of spaghetti
that I have my doubts, but the tests are green.
The patch is based on the observation that the em-http-request call
sequence goes:
1. `HttpConnection#activate_connection`
2. `HttpClient#connection_completed`
3. `HttpClient#send_request`
The `#connection_completed` method is normally responsible for calling
the request middleware before passing the adjusted headers/body to
`#send_request` (cf.
https://github.com/igrigorik/em-http-request/blob/34919d760b940dfd27159bbebce5c4dac9845eb6/lib/em-http/client.rb#L53-L62).
But webmock needs the request signature all the way back in
`#activate_connection`, which we want to compute using the
middleware-adjusted headers/body.
So instead, we let `#activate_connection` handle building …
=> Avoid redundantly calling em-http-request middleware

webmock.gemspec
=> skip em-* gems on jruby

lib/webmock/request_pattern.rb, spec/unit/request_pattern_spec.rb
Fixes https://github.com/bblimke/webmock/issues/983
=> add support for top level array in request pattern

lib/webmock/util/hash_counter.rb
Thanks for publishing and maintaining this great library!!
Issue#
------
`No-Story`
Description:
------
Refactored level WebMock::Util::HashCounter
=> Refactor WebMock::Util::HashCounter

README.md
Noticed there was some odd indentation in the README, quick patch to normalize that.
=> README.md Spacing Fixes

CHANGELOG.md
The latest entry is released with v3.19.1.
=> Fix a changelog entry for v3.19.1

lib/webmock/util/headers.rb
since frozen_string_literal magic comment added.
=> Remove redundant freeze

lib/webmock/http_lib_adapters/net_http.rb
=> Fix typo: `alredy` → `already`
